#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=4:00:00
#PBS -N endpointGen
#PBS -V

set -e

mkdir -p freesurfer/mri

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;

if [ ! -f freesurfer/mri/aparc+aseg.nii.gz ]; then
    echo "creating gm mask"
    time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convertgmmask.sh"
fi

echo "generating endpoints"

#trying to workaround the issue of 
# -- Could not access the MATLAB Runtime component cache. Details: fl:filesystem:NotDirectoryError
export SINGULARITYENV_MCR_CACHE_ROOT=`pwd`

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/bsc_classifiedStreamEndpointCortex_BL
